name: Run tests in SmallTalk
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Cuis University
        run: ./.github/workflows/installCuis.sh
      - name: "Run tests: ReceptiveAccount"
        run: ./.github/workflows/runTests.sh ServiciosFinancieros-Ejercicio ReceptiveAccountTest
      - name: Install Cuis University
        run: ./.github/workflows/installCuis.sh
      - name: "Run tests: Portfolio"
        run: ./.github/workflows/runTests.sh ServiciosFinancieros-Ejercicio PortfolioTest
      - name: Install Cuis University
        run: ./.github/workflows/installCuis.sh
      - name: "Run tests: Transfer"
        run: ./.github/workflows/runTests.sh ServiciosFinancieros-Ejercicio TransferTest
      - name: Install Cuis University
        run: ./.github/workflows/installCuis.sh
      - name: "Run tests: AccountSummary"
        run: ./.github/workflows/runTests.sh ServiciosFinancieros-Ejercicio AccountSummaryTest
      - name: Install Cuis University
        run: ./.github/workflows/installCuis.sh
      - name: "Run tests: TransferNetSummary"
        run: ./.github/workflows/runTests.sh ServiciosFinancieros-Ejercicio TransferNetSummaryTest
